/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: {
          DEFAULT: '#fcf8fa',
          dim: '#dcd9db',
          bright: '#fcf8fa',
          'container-lowest': '#ffffff',
          'container-low': '#f6f3f5',
          'container': '#f0edef',
          'container-high': '#eae7e9',
          'container-highest': '#e4e2e4',
        },
        'on-surface': {
          DEFAULT: '#102f71',
          variant: '#45464d',
        },
        'inverse-surface': '#303032',
        'inverse-on-surface': '#f3f0f2',
        outline: {
          DEFAULT: '#76777d',
          variant: '#c6c6cd',
        },
        'surface-tint': '#565e74',
        primary: {
          DEFAULT: '#000000',
          on: '#ffffff',
          container: '#131b2e',
          'on-container': '#7c839b',
          inverse: '#bec6e0',
          fixed: '#dae2fd',
          'fixed-dim': '#bec6e0',
          'on-fixed': '#131b2e',
          'on-fixed-variant': '#3f465c',
        },
        secondary: {
          DEFAULT: '#7fb445',
          on: '#ffffff',
          container: '#7fb445',
          'on-container': '#7fb445',
          fixed: '#7fb445',
          'fixed-dim': '#7fb445',
          'on-fixed': '#7fb445',
          'on-fixed-variant': '#7fb445',
        },
        tertiary: {
          DEFAULT: '#000000',
          on: '#ffffff',
          container: '#0b1c30',
          'on-container': '#75859d',
          fixed: '#d3e4fe',
          'fixed-dim': '#b7c8e1',
          'on-fixed': '#0b1c30',
          'on-fixed-variant': '#38485d',
        },
        error: {
          DEFAULT: '#ba1a1a',
          on: '#ffffff',
          container: '#ffdad6',
          'on-container': '#93000a',
        },
        background: '#fcf8fa',
        'on-background': '#102f71',
        'surface-variant': '#e4e2e4',
      },
      fontFamily: {
        sans: ['"Google Sans"', 'Inter', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'display-lg': ['36px', { lineHeight: '44px', fontWeight: '700', letterSpacing: '-0.02em' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600', letterSpacing: '-0.01em' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-mono': ['13px', { lineHeight: '16px', fontWeight: '500' }],
        'label-caps': ['12px', { lineHeight: '16px', fontWeight: '700', letterSpacing: '0.05em' }],
        'headline-md-mobile': ['20px', { lineHeight: '28px', fontWeight: '600' }],
      },
      borderRadius: {
        sm: '0.125rem',
        DEFAULT: '0.25rem',
        md: '0.375rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        unit: '4px',
        gutter: '16px',
        'margin-mobile': '16px',
        'margin-desktop': '32px',
        'stack-sm': '8px',
        'stack-md': '16px',
        'stack-lg': '24px',
      },
      boxShadow: {
        'level-1': 'none',
        'level-2': '0 1px 4px rgba(0, 0, 0, 0.1)',
        'level-3': '0 8px 24px rgba(0, 0, 0, 0.15)',
      },
    },
  },
  plugins: [],
}
