# Generated by Django 5.2.16 on 2026-07-27 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='nparequest',
            name='valid_npa_status_check',
        ),
        migrations.RenameIndex(
            model_name='deliverynote',
            new_name='bost_delive_deliver_9d1ac3_idx',
            old_name='bost_dn_num_idx',
        ),
        migrations.RenameIndex(
            model_name='deliverynote',
            new_name='bost_delive_created_ab1075_idx',
            old_name='bost_dn_created_idx',
        ),
        migrations.RenameIndex(
            model_name='dispatchrequest',
            new_name='bost_dispat_status_4bf52a_idx',
            old_name='bost_dr_status_stage_idx',
        ),
        migrations.RenameIndex(
            model_name='dispatchrequest',
            new_name='bost_dispat_lot_id_abd961_idx',
            old_name='bost_dr_lot_idx',
        ),
        migrations.RenameIndex(
            model_name='dispatchrequest',
            new_name='bost_dispat_created_f6441d_idx',
            old_name='bost_dr_created_idx',
        ),
        migrations.RenameIndex(
            model_name='lot',
            new_name='bost_lots_status_42d31f_idx',
            old_name='bost_lots_status_idx',
        ),
        migrations.RenameIndex(
            model_name='nparequest',
            new_name='bost_npa_re_status_ee73f1_idx',
            old_name='bost_npa_status_idx',
        ),
        migrations.RenameIndex(
            model_name='nparequest',
            new_name='bost_npa_re_depot_i_d27bda_idx',
            old_name='bost_npa_depot_status_idx',
        ),
        migrations.RenameIndex(
            model_name='nparequest',
            new_name='bost_npa_re_npa_ref_32f88c_idx',
            old_name='bost_npa_ref_idx',
        ),
        migrations.RenameIndex(
            model_name='tanker',
            new_name='bost_tanker_status_f5234d_idx',
            old_name='bost_tankers_status_idx',
        ),
        migrations.RenameIndex(
            model_name='waybill',
            new_name='bost_waybil_waybill_a6f79e_idx',
            old_name='bost_wb_num_idx',
        ),
        migrations.RenameIndex(
            model_name='waybill',
            new_name='bost_waybil_tanker__7af863_idx',
            old_name='bost_wb_tanker_idx',
        ),
        migrations.RenameIndex(
            model_name='waybill',
            new_name='bost_waybil_created_14ca3c_idx',
            old_name='bost_wb_created_idx',
        ),
        migrations.AddField(
            model_name='nparequest',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nparequest',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='nparequest',
            name='contact_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='nparequest',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='nparequest',
            name='customer_company',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='nparequest',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nparequest',
            name='delivery_location',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='nparequest',
            name='delivery_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nparequest',
            name='denial_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nparequest',
            name='denied_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='denied_npa_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nparequest',
            name='driver_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='nparequest',
            name='driver_phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='nparequest',
            name='held_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='held_npa_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nparequest',
            name='hold_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nparequest',
            name='hold_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nparequest',
            name='loaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loaded_npa_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nparequest',
            name='loading_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nparequest',
            name='permit_id',
            field=models.CharField(blank=True, help_text='Permit identifier issued once the depot manager grants authorisation.', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='nparequest',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='nparequest',
            name='quantity_loaded',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual quantity dispensed into the vehicle.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='nparequest',
            name='tanker',
            field=models.ForeignKey(blank=True, help_text='Registered tanker matched to this order, if one exists.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='npa_requests', to='dispatch.tanker'),
        ),
        migrations.AddField(
            model_name='nparequest',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='nparequest',
            name='truck_number',
            field=models.CharField(blank=True, help_text='Car/plate number declared by the customer at order time.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='nparequest',
            name='unit',
            field=models.CharField(choices=[('LITERS', 'Liters'), ('GALLONS', 'Gallons')], default='LITERS', max_length=10),
        ),
        migrations.AddField(
            model_name='nparequest',
            name='verified_truck_number',
            field=models.CharField(blank=True, help_text='Car number physically observed at the loading bay gate.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dispatchrequest',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted (Pending Manager)'), ('MANAGER_APPROVED', 'Manager Approved / Permit Issued (Pending Customs)'), ('REJECTED', 'Rejected by Manager'), ('CUSTOMS_APPROVED', 'Customs Signed Off (Pending Lot Clearance)'), ('ON_HOLD', 'On Hold (Customs Query Raised)'), ('LOT_CLEARED', 'Lot Cleared (Authorized for Filling)'), ('LOADING', 'Vehicle Loading'), ('COMPLETED', 'Completed (Waybill Issued)'), ('DENIED', 'Entry Denied (Vehicle Discrepancy)')], default='SUBMITTED', max_length=30),
        ),
        migrations.AlterField(
            model_name='nparequest',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted (Pending Manager)'), ('MANAGER_APPROVED', 'Manager Approved / Permit Issued (Pending Customs)'), ('REJECTED', 'Rejected by Manager'), ('CUSTOMS_APPROVED', 'Customs Signed Off (Pending Lot Clearance)'), ('ON_HOLD', 'On Hold (Customs Query Raised)'), ('LOT_CLEARED', 'Lot Cleared (Authorized for Filling)'), ('LOADING', 'Vehicle Loading'), ('COMPLETED', 'Completed (Waybill Issued)'), ('DENIED', 'Entry Denied (Vehicle Discrepancy)')], default='SUBMITTED', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='nparequest',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['SUBMITTED', 'MANAGER_APPROVED', 'REJECTED', 'CUSTOMS_APPROVED', 'ON_HOLD', 'LOT_CLEARED', 'LOADING', 'COMPLETED', 'DENIED'])), name='valid_npa_status_check'),
        ),
    ]
