# Generated by Django 5.1.15 on 2026-09-09 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dispatch", "0002_remove_nparequest_valid_npa_status_check_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="nparequest",
            name="compartments",
            field=models.PositiveSmallIntegerField(
                default=4, help_text="Number of BRV tanker compartments."
            ),
        ),
        migrations.AddField(
            model_name="nparequest",
            name="product_group",
            field=models.CharField(
                default="WHITE PRODUCT",
                help_text="NPA Product Group (e.g. WHITE PRODUCT for refined fuels).",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="nparequest",
            name="product_type",
            field=models.CharField(
                help_text="Official NPA product code (AGO, PMS, DPK, ATK, MGO).",
                max_length=50,
            ),
        ),
    ]
