# Generated by Django 5.1.15 on 2026-09-09 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dispatch", "0003_nparequest_compartments_nparequest_product_group_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nparequest",
            name="product_type",
            field=models.CharField(
                help_text="Official NPA product code (AGO, PMS, DPK).", max_length=50
            ),
        ),
    ]
