# Generated by Django 5.2.16 on 2026-07-27 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='user',
            new_name='bost_users_role_3d8778_idx',
            old_name='bost_users_role_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='bost_users_depot_i_df92ee_idx',
            old_name='bost_users_depot_id_idx',
        ),
        migrations.AddField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, help_text='Customer company this user belongs to (customers only).', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='depot_id',
            field=models.CharField(blank=True, help_text='Associated Depot identifier.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'Customer Company'), ('MANAGER', 'Manager'), ('CUSTOMS_OFFICER', 'Customs Officer'), ('DEPOT_OPERATOR', 'Depot Operator'), ('ADMIN', 'Administrator')], default='DEPOT_OPERATOR', help_text='System role defining workflow approval permissions.', max_length=30),
        ),
    ]
