# Generated by Django 5.1.15 on 2026-09-09 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "users",
            "0002_rename_bost_users_role_idx_bost_users_role_3d8778_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("MANAGER", "Manager"),
                    ("CUSTOMS_OFFICER", "Customs Officer"),
                    ("DEPOT_OPERATOR", "Depot Operator"),
                    ("ADMIN", "Administrator"),
                ],
                default="DEPOT_OPERATOR",
                help_text="System role defining workflow approval permissions.",
                max_length=30,
            ),
        ),
    ]
